version: '3.8'

services:
  postgres:
    image: postgres:15.4
    restart: always
    container_name: fullstack-nextjs-app-postgres
    hostname: docker-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:
